parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

framework:
    secret: %secret%
    serializer: true
    validation:
        enable_annotations: true
    annotations:
        cache: none

monolog:
    handlers:
        console:
            type: console
