parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

framework:
    secret: '%secret%'
    http_method_override: false
    validation:
        enable_annotations: true
    annotations:
        cache: none

monolog:
    handlers:
        console:
            type: service
            id: nab3a.logger.handler
