services:
    nab3a.console.application:
        class: Symfony\Component\Console\Application
        arguments:
            - 'nab3a'
            - '@@package_version@'
        calls:
            - [ setDispatcher, [ "@event_dispatcher" ] ]

    nab3a.console.command:
        abstract: true
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: monolog.logger }

    nab3a.console.no_kernel_command_listener:
        class: Nab3aBundle\Console\NoKernelCommandListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommand  }