parameters: ~

services:
    console.application:
        class: Nab3aBundle\Console\Application
        arguments:
            - 'nab3a'
        calls:
            - [ setDispatcher, [ "@event_dispatcher" ] ]
            - [ setContainer, [ "@service_container" ] ]

    command:
        abstract: true
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger }
