services:
    nab3a.event_loop:
        class: React\EventLoop\LoopInterface
        factory: ['React\EventLoop\Factory','create']

    nab3a.event_loop.configurator:
        class: Nab3aBundle\EventLoop\Configurator
        public: false
