services:
    nab3a.event_loop:
        class: React\EventLoop\LoopInterface
        factory: ['React\EventLoop\Factory','create']
        public: false
        calls:
            - [ futureTick, [ '@nab3a.guzzle.task_queue.listener' ] ]

