services:
    nab3a.event_loop.default:
        class: React\EventLoop\LoopInterface
        factory: ['React\EventLoop\Factory','create']
        public: false

    nab3a.event_loop:
        alias: nab3a.event_loop.default

