parameters:

services:
    nab3a.guzzle.middleware.history:
        class: Nab3aBundle\Guzzle\HistoryMiddlewarePlugin
        public: false
        tags:
            - { name: guzzle.middleware, id: nab3a.guzzle.client }

    nab3a.guzzle.middleware.retry:
        class: Nab3aBundle\Guzzle\RetryMiddlewarePlugin
        public: false
        tags:
            - { name: guzzle.middleware, id: nab3a.guzzle.client }

    nab3a.guzzle.middleware.oauth:
        class: Nab3aBundle\Guzzle\OauthMiddlewarePlugin
        abstract: true
        public: false

    nab3a.guzzle.middleware.log:
        class: Nab3aBundle\Guzzle\LoggingMiddlewarePlugin
        calls:
            - [ setLogger, ['@logger'] ]
        tags:
            - { name: monolog.logger, channel: guzzle }
            - { name: guzzle.middleware, id: nab3a.guzzle.client }
        public: false

    nab3a.guzzle.client:
        class: GuzzleHttp\Client
        public: false
        abstract: true

    nab3a.guzzle.task_queue:
        class: GuzzleHttp\Promise\TaskQueue
        factory: GuzzleHttp\Promise\queue

    nab3a.guzzle.emitter:
        class: Nab3aBundle\Guzzle\Emitter
        calls:
            - [ setLogger, [ '@logger']]
        tags:
            - { name: monolog.logger, channel: guzzle }

    nab3a.guzzle.event_loop.plugin:
        class: Nab3aBundle\Guzzle\EventLoopPlugin
        public: false
        tags:
            - { name: event_loop.plugin, id: nab3a.event_loop }
