parameters:

services:
    guzzle.middleware.history:
        class: Nab3aBundle\Guzzle\HistoryMiddlewarePlugin
        public: false

    guzzle.stack.configurator:
        class: Nab3aBundle\Guzzle\Configurator
        public: false
        abstract: true

    guzzle.stack:
        class: GuzzleHttp\HandlerStack
        abstract: true
        factory: [ '@guzzle.stack.configurator', create ]
        configurator: [ '@guzzle.stack.configurator', 'configure' ]

    guzzle.middleware.retry:
        class: Nab3aBundle\Guzzle\RetryMiddlewarePlugin

    guzzle.middleware.oauth:
        class: Nab3aBundle\Guzzle\OauthMiddlewarePlugin
        abstract: true
        public: false

    guzzle.middleware.log:
        class: Nab3aBundle\Guzzle\LoggingMiddlewarePlugin
        public: false
        calls:
            - [ setLogger, ['@logger'] ]
        tags:
            - { name: monolog.logger, channel: guzzle }
        public: false

    guzzle.client:
        class: GuzzleHttp\Client
        abstract: true

    guzzle.task_queue:
        class: GuzzleHttp\Promise\TaskQueue
        factory: GuzzleHttp\Promise\queue

    guzzle.emitter:
        class: Nab3aBundle\Guzzle\Emitter
        calls:
            - [ setLogger, [ '@logger']]
        tags:
            - { name: monolog.logger, channel: guzzle }

    monolog.processor.memory_usage:
        class: Monolog\Processor\MemoryUsageProcessor
        tags:
            - { name: monolog.processor }
