parameters:
    serializer.mapping.cache.prefix: ''

services:
    serializer:
        class: Symfony\Component\Serializer\Serializer

    serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        public: false
        tags:
            - { name: serializer.normalizer, priority: -1000 }
        arguments: ['@serializer.mapping.class_metadata_factory', null, '@serializer.property_accessor']

    serializer.mapping.chain_loader:
        class: Symfony\Component\Serializer\Mapping\Loader\LoaderChain
        public: false
        arguments: [~]

    serializer.mapping.class_metadata_factory:
        class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
        public: false
        arguments: ['@serializer.mapping.chain_loader', null]

    serializer.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder
        public: false
        tags:
            - { name: serializer.encoder }

    serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        public: false
        tags:
            - { name: serializer.encoder }

    serializer.name_converter.camel_case_to_snake_case:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
        public: false

    serializer.property_accessor:
        alias: property_accessor
        public: false
