services:
    monolog.processor.memory_usage:
        class: Monolog\Processor\MemoryUsageProcessor
        tags:
            - { name: monolog.processor }

    event_loop:
        class: React\EventLoop\LoopInterface
        factory: ['React\EventLoop\Factory','create']
        configurator: ['@event_loop.configurator', configure ]

    event_loop.configurator:
        class: Nab3aBundle\EventLoop\Configurator
        arguments:
            -
                - '@guzzle.event_loop.plugin'

    guzzle.event_loop.plugin:
        class: Nab3aBundle\Guzzle\EventLoopPlugin
        public: false
