services:
    nab3a.stream.command:
        class: Nab3aBundle\Command\StreamCommand
        calls:
            - [ setContainer, [ "@service_container" ]]
        tags:
            - { name: console.command, app: nab3a }

    nab3a.validate.command:
        class: Nab3aBundle\Command\ValidationCommand
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: console.command, app: nab3a }
