services:
    nab3a.stream.command:
        class: Nab3aBundle\Command\StreamCommand
        parent: nab3a.console.command
        tags:
            - { name: nab3a.console.command }

    nab3a.stream_stdout.command:
        class: Nab3aBundle\Command\StreamStdoutCommand
        parent: nab3a.console.command
        tags:
            - { name: nab3a.console.command }

    nab3a.validate.command:
        class: Nab3aBundle\Command\ValidationCommand
        parent: nab3a.console.command
        tags:
            - { name: nab3a.console.command }

    nab3a.stream.eep:
        class: Nab3aBundle\Stream\Eep
        arguments: [ '@nab3a.event_loop']
        calls:
            - [ setLogger, ['@logger']]
            - [ setContainer, ['@service_container']]
        tags:
            - { name: evenement.plugin, id: nab3a.twitter.message_emitter }

    nab3a.stream.eep.idle_time:
        class: React\EEP\Window\Periodic
        factory: ['@nab3a.stream.eep', makeIdleTimeTracker ]

    nab3a.stream.eep.status_counter:
        class: React\EEP\Window\Periodic
        factory: ['@nab3a.stream.eep', makeStatusCounter ]
