services:
    nab3a.stream.command:
        class: Nab3aBundle\Command\StreamCommand
        calls:
            - [ setContainer, [ "@service_container" ]]
        tags:
            - { name: nab3a.console.command }

    nab3a.validate.command:
        class: Nab3aBundle\Command\ValidationCommand
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: nab3a.console.command }
