parameters:
    nab3a.twitter.output.pattern: 'data/{user.screen_name}/{created_at.date}/{id}.json'
    nab3a.twitter.batch_output.pattern: 'data/{id}.json'

services:
    nab3a.twitter.message_emitter:
        class: Nab3aBundle\Stream\MessageEmitter
        arguments: ['@nab3a.twitter.guesser.event_type']

    nab3a.twitter.guesser.event_type:
        class: Nab3aBundle\Stream\TypeGuesser
        public: false

    nab3a.twitter.message_emitter.plugin.logging:
        class: Nab3aBundle\Logger\LogMessagePlugin
        calls:
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: monolog.logger, channel: twitter }
            # - { name: evenement.plugin, id: nab3a.twitter.message_emitter }
        public: false

    nab3a.twitter.request_factory:
        class: Nab3aBundle\Stream\RequestFactory
        arguments: [ '@nab3a.twitter.guzzle.client', { delimited: length } ]

    nab3a.twitter.stream_factory:
        class: Nab3aBundle\Stream\StreamFactory
        shared: false
        arguments: [ '@nab3a.event_loop' ]

    nab3a.twitter.guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: https://stream.twitter.com/1.1/
                auth: oauth
                decode_content: 'deflate, gzip'
                stream: true
                on_stats: [ '@nab3a.guzzle.emitter', 'onStats' ]
                on_headers: [ '@nab3a.guzzle.emitter', 'onHeaders' ]

    nab3a.twitter.guzzle.middleware.oauth:
        parent: nab3a.guzzle.middleware.oauth
        arguments:
            -
                consumer_key:    '@=nab3a_parameter(''nab3a.twitter.consumer_key'')'
                consumer_secret: '@=nab3a_parameter(''nab3a.twitter.consumer_secret'')'
                token:           '@=nab3a_parameter(''nab3a.twitter.access_token'')'
                token_secret:    '@=nab3a_parameter(''nab3a.twitter.access_token_secret'')'
        tags:
            - { name: guzzle.middleware, id: nab3a.twitter.guzzle.client }

    nab3a.twitter.file_output:
        class: Nab3aBundle\Output\FileOutputPlugin
        arguments: [%nab3a.twitter.output.pattern%, '@filesystem']
#        tags:
#            - { name: evenement.plugin, id: nab3a.twitter.message_emitter }
