services:
    nab3a.twitter.message_emitter:
        class: Nab3aBundle\Stream\MessageEmitter
        arguments: ['@nab3a.twitter.guesser.event_type']

    nab3a.twitter.guesser.event_type:
        class: Nab3aBundle\Stream\TypeGuesser
        public: false

    nab3a.twitter.message_emitter.plugin.logging:
        class: Nab3aBundle\Logger\LogMessagePlugin
        calls:
            - [ setLogger, [ "@?logger" ] ]
        tags:
            - { name: monolog.logger, channel: twitter }
            - { name: evenement.plugin, id: nab3a.twitter.message_emitter }
        public: false

    nab3a.twitter.request_factory:
        class: Nab3aBundle\Stream\RequestFactory
        arguments: [ '@nab3a.twitter.guzzle.client', { delimited: length } ]

    nab3a.twitter.stream_factory:
        class: Nab3aBundle\Stream\StreamFactory
        arguments: [ '@nab3a.event_loop' ]

    nab3a.twitter.guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: https://stream.twitter.com/1.1/
                auth: oauth
                decode_content: 'deflate, gzip'
                stream: true

    nab3a.twitter.guzzle.middleware.retry:
        parent: nab3a.guzzle.middleware.retry
        tags:
            - { name: guzzle.middleware, id: nab3a.twitter.guzzle.client }

    nab3a.twitter.guzzle.middleware.log:
        parent: nab3a.guzzle.middleware.log
        tags:
            - { name: guzzle.middleware, id: nab3a.twitter.guzzle.client }

    nab3a.twitter.guzzle.middleware.history:
        parent: nab3a.guzzle.middleware.history
        tags:
            - { name: guzzle.middleware, id: nab3a.twitter.guzzle.client }

    nab3a.twitter.guzzle.middleware.oauth:
        parent: nab3a.guzzle.middleware.oauth
        arguments:
            -
                consumer_key:    "@=service('nab3a.standalone.parameters').get('nab3a.twitter.consumer_key')"
                consumer_secret: "@=service('nab3a.standalone.parameters').get('nab3a.twitter.consumer_secret')"
                token:           "@=service('nab3a.standalone.parameters').get('nab3a.twitter.access_token')"
                token_secret:    "@=service('nab3a.standalone.parameters').get('nab3a.twitter.access_token_secret')"
        tags:
            - { name: guzzle.middleware, id: nab3a.twitter.guzzle.client }
